# Usando Node para construir o app
FROM node:20-alpine AS build

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código e builda
COPY . .
RUN npm run build

# Serve os arquivos estáticos usando Nginx
FROM nginx:alpine

# Copia build para o Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expõe a porta do Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
